#########################
### AUTH
########################

### Register
POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "wilfred",
    "password": "password"
}

### Retrieve All Users
GET http://localhost:5000/register
Content-Type: application/json



### Login and get Access Token
POST http://localhost:5000/auth
Content-Type: application/json

{
    "username": "wilfred",
    "password": "password"
}


##########################
### AUTH
#########################

@Token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTY5MTk3NjEsImlhdCI6MTU5NjgzMzM2MSwibmJmIjoxNTk2ODMzMzYxLCJpZGVudGl0eSI6MX0.TjoBC7fJM83aDHqP9k-6Z6zHeAPSUry47LPKAg-wqTo
@Name = testing

#########################
### ITEMS
########################

### GET ALL ITEMS
GET http://localhost:5000/items
Content-Type: application/json
Authorization: JWT {{Token}}

### GET ONE ITEM
GET http://localhost:5000/item/{{Name}}
Content-Type: application/json
Authorization: JWT {{Token}}

### CREATE ITEM
POST http://localhost:5000/item/{{Name}}
Content-Type: application/json
Authorization: JWT {{Token}}

{
    "price": 15.00,
    "store_id": 1
}

### Delete ITEM 

DELETE http://localhost:5000/item/{{Name}}
Authorization: JWT {{Token}}

### Update ITEM 
PUT http://localhost:5000/item/{{Name}}
Authorization: JWT {{Token}}
Content-Type: application/json

{
    "price": 1.99,
      "store_id": 1
}



#################
# STORES
################
@StoreName = AtyStore
### GET ALL STORES
GET http://localhost:5000/stores
Content-Type: application/json
Authorization: JWT {{Token}}


### GET ONE STORE
GET http://localhost:5000/store/{{StoreName}}
Content-Type: application/json
Authorization: JWT {{Token}}

### CREATE STORE
POST http://localhost:5000/store/{{StoreName}}
Content-Type: application/json
Authorization: JWT {{Token}}

### Delete STORE 

DELETE http://localhost:5000/store/{{StoreName}}
Authorization: JWT {{Token}}
