#########################
### AUTH
########################

### Register
POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "wilfred",
    "password": "password"
}

### Retrieve All Users (just for test)
GET http://localhost:5000/register
Content-Type: application/json


### Login and get Access Token
POST http://localhost:5000/auth
Content-Type: application/json

{
    "username": "wilfred",
    "password": "password"
}




##########################
### TOKEN
#########################

@Token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTY4NTIzNzMsIm5iZiI6MTU5Njg1MjM3MywianRpIjoiNzA4MmEzNWQtMjk5YS00NjdmLTllNmEtZjk4ZWFlMTNjNTMzIiwiZXhwIjoxNTk2ODUzMjczLCJpZGVudGl0eSI6MSwiZnJlc2giOnRydWUsInR5cGUiOiJhY2Nlc3MiLCJ1c2VyX2NsYWltcyI6eyJpc19hZG1pbiI6dHJ1ZX19.q0bevWMGNjFdhoFS1EGnmqsqA-seW0lwwscjCQuiax0

##########################
### USER ROUTES
##########################
### Retrieve User by id
GET http://localhost:5000/user/2
Content-Type: application/json
Authorization: Bearer {{Token}}

### LOGOUT
POST  http://localhost:5000/logout
Content-Type: application/json
Authorization: Bearer {{Token}}

### Delete User by id
DELETE  http://localhost:5000/user/2
Content-Type: application/json
Authorization: Bearer {{Token}}

### Get Access token with refresh token
POST http://localhost:5000/refresh
Content-Type: application/json
Authorization: Bearer REFRESH_TOKEN_HERE


#########################
### ITEMS
########################
@Name = testing

### GET ALL ITEMS
GET http://localhost:5000/items
Content-Type: application/json
Authorization: Bearer {{Token}}

### GET ONE ITEM
GET http://localhost:5000/item/{{Name}}
Content-Type: application/json
Authorization: Bearer {{Token}}

### CREATE ITEM
POST http://localhost:5000/item/{{Name}}
Content-Type: application/json
Authorization: Bearer {{Token}}

{
    "price": 15.00,
    "store_id": 1
}

### Delete ITEM 

DELETE http://localhost:5000/item/{{Name}}
Authorization: Bearer {{Token}}

### Update ITEM 
PUT http://localhost:5000/item/{{Name}}
Content-Type: application/json
Authorization: Bearer {{Token}}

{
    "price": 1.99,
      "store_id": 1
}



#################
# STORES
################
@StoreName = AtyStore
### GET ALL STORES
GET http://localhost:5000/stores
Content-Type: application/json
Authorization: Bearer {{Token}}


### GET ONE STORE
GET http://localhost:5000/store/{{StoreName}}
Content-Type: application/json
Authorization: Bearer {{Token}}

### CREATE STORE
POST http://localhost:5000/store/{{StoreName}}
Content-Type: application/json
Authorization: Bearer {{Token}}

### Delete STORE 

DELETE http://localhost:5000/store/{{StoreName}}
Authorization: Bearer {{Token}}
